### ISSUE TITLE
001/Update-ajustes-desempenho-padrão-python

### ISSUE THREAD

**Issue by ClasRCDM** [Gustavosta/TabNews.py#1]
# Ajustes...
Hey, eu di uma olhada em toda a biblioteca e vi não estava no totalmente no padrão de identação do python.
- Alem de varias brechas para melhorar o desempenho, então eu fiz varias melhorias em todo o código
- junto com a padronização da identação, ainda a espaço para melhorar o desempenho porem não fui muito alem
- para não modificar demas o código original.

---
### - Fors
1. ```Fors em iteradores.```
2. ```Utilização da list comprehension.```

### - If Else
1. ```Remoção de else desnecessários.```
2. ```Ajuste de definição de variveis usando uma linha.```

Também otimizei as importação das bibliotecas.

## Identação e Padrão Python
Ajustei todo o código para seguir o PEP8

# Arquivo com as modificações!
[TabNewsDesempenho.zip](https://github.com/Gustavosta/TabNews.py/files/10297023/TabNewsDesempenho.zip)

**Comment by Gustavosta** [comment]
**Aopa [ClasRCDM](https://github.com/ClasRCDM)!** Peço mil desculpas pela demora em responder! **Muito muito obrigado por estar contribuindo para essa biblioteca**, eu realmente não esperava alguma contribuição assim tão cedo, haha.

Vi todo o código que você enviou, e realmente, **ele tá bem melhor de se ver e bem mais ajustado com o PEP8**. A questão de má identação, acho que o maior responsável por isso são as extenções de auto-identação que uso no VS Code. E a questão de de uso de muitos ifs e elses, além da repetição de parte do código, **é realmente uma coisa que devo melhorar**, e querendo ou não, **isso me ajudou a ver o que eu podia ter melhorado**. 

Essa é **minha segunda biblioteca** e me inspirei em algumas coisas do [InstagrAPI](https://github.com/adw0rd/instagrapi), como a estrutura. E se comparado a primeira, que é a [PIX Utils](https://github.com/Gustavosta/pix-utils) (que é uma lib de utilitários para chaves PIX), acho que **está bem melhor**kk.

Acho que da próxima vez, seria interessante se você **abrisse uma [PR](https://github.com/Gustavosta/TabNews.py/pulls) para esse tipo de coisa**, daí acho que seria melhor de visualizar o código. Mas, novamente, **muito obrigado mesmo por isso!** 🤝 :)

**Comment by ClasRCDM** [comment]
Opa mano, pode deixar vou usar PR na próxima qualquer duvida sobre desempenho só fala comigo

**Comment by Gustavosta** [comment]
Beleza e obrigado mano! Estou fechando essa issue no momento, mas pode ficar a vontade para reabrir quando precisar! :)
