### ISSUE TITLE
Erro no paramentro [use_preview_tabnews_host=True]

### ISSUE THREAD

**Issue by thisiscleverson** [Gustavosta/TabNews.py#2]
Ao tentar passar o paramentro `use_preview_tabnews_host=True` no Client: `client = Client(EMAIL, PASS, use_preview_tabnews_host=True)`
aparece um erro:

```shell
 line 32, in <genexpr>
 if value[0][deployment['environment'].lower()]
 KeyError: 'production'
```

**Comment by Gustavosta** [comment]
Resolvido na [PR #3](https://github.com/Gustavosta/TabNews.py/pull/3).
